sequenceDiagram
  actor a as Author
  actor r as Reviewers
  participant b as Blockchain
  a ->> b: data object
  b ->> b: pick reviewers
  b ->> r: data object
  r ->> b: review
  b ->> b: consensus
