sequenceDiagram
  actor a as Author
  participant b as Blockchain
  actor r as Reviewers
  a ->> b: {instruction, response, source}
  b ->> b: pick reviewers
  b ->> r: reqest to review \n{instruction, response, source}
  r ->> b: vote
  b ->> b: decision
